// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/mocks/mock_get_weather.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/features/weather/domain/entities/weather.dart'
    as _i3;
import 'package:weather_app/features/weather/domain/repositories/weather_repository.dart'
    as _i2;
import 'package:weather_app/features/weather/domain/usecases/get_weather.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherRepository_0 extends _i1.SmartFake
    implements _i2.WeatherRepository {
  _FakeWeatherRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeather_1 extends _i1.SmartFake implements _i3.Weather {
  _FakeWeather_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetWeather].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeather extends _i1.Mock implements _i4.GetWeather {
  MockGetWeather() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWeatherRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WeatherRepository);

  @override
  _i5.Future<_i3.Weather> call(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#call, [city]),
            returnValue: _i5.Future<_i3.Weather>.value(
              _FakeWeather_1(this, Invocation.method(#call, [city])),
            ),
          )
          as _i5.Future<_i3.Weather>);
}
